### ISSUE TITLE
Monitoring mode is not available [sunrise_driver_original]

### ISSUE THREAD

**Issue by Svastits** [kroshu/ros2_kuka_drivers#23]
When activating only the 2 driver nodes, the monitoring mode is activated on the robot controller, but the _activate()_ function of the _RobotObserver_ class is not called, therefore the publisher is not activated and the joint states are not sent to the ROS2 side
Besides, the _ConfigurationManager_ contains two client requests to sync the _receive_multiplier_ and the _send_period_  parameters with the joint_controller, which is not available with only the 2 drivers started, so configuration fails

Solution proposal:
- if monitoring mode is a wanted feature, add a _commanding_ (_bool_) parameter to the node and call these syncing requests only if the parameter is false + move the activation of the _RobotObserver_ to the LifeCycleNode activation function
- if monitoring mode is not needed, the syncing should remain as it is, and the whole commanding mode activation should be moved to the activation callback of the _robot_manager_node_ (currently done in the _changeRobotCommandingState()_ method of the _system_manager_)

**Comment by Groebehavn** [comment]
@resizoltan This will not be supported by the driver officially, there is a branch, referenced here, on which this probably could be solved if needed.
