### ISSUE TITLE
Client app thread can't be joined if START_FRI fails [sunrise_driver_original]

### ISSUE THREAD

**Issue by Svastits** [kroshu/ros2_kuka_drivers#27]
If the START_FRI command fails, the driver tries to transition back to inactive state, which means joining the _client_app_thread__ of the _robot_control_node_. In this specific case, the thread blocks at the following command:
success = client_application_->step();

**Reason**:
The _robot_control_node_ is activated before the starting of FRI, so the loop of the client app starts, but FRI is not started, therefore the step() function blocks forever, the loop condition is not tested again.

**Possible solutions:**
- change the order of activation?
- add synchronization method to force client application thread to wait for successful starting of FRI

**Comment by Groebehavn** [comment]
@resizoltan This will not be supported by the driver officially, there is a branch, referenced here, on which this probably could be solved if needed.
